### ISSUE TITLE
RN64 Hermes iOS: No console.logs anymore: "JavaScript logs will appear in your environment console"

### ISSUE THREAD

**Issue by mrousavy** [facebook/metro#635]
Since I upgraded from RN 0.63 to RN 0.64 (rc3) and enabled Hermes I cannot see my console.logs anymore.

![Screenshot 2021-02-09 at 14 05 40](https://user-images.githubusercontent.com/15199031/107367690-e52b3f00-6adf-11eb-8259-f60ea490e7e1.png)

The same thing in Flipper Logs.

* iOS with Hermes: no logs ❌
* iOS with JSC: logs ✅
* Android with Hermes: logs ✅
* Android with JSC: logs ✅

Out put of `npx react-native --version`:
```
5.0.1-alpha.1
```

## Probably related

* https://github.com/facebook/flipper/issues/1913
* https://github.com/react-native-community/releases/issues/214#issuecomment-775899526

**Comment by alloy** [comment]
@mrousavy I have no clear ideas offhand, but would suggest you start debugging from [here](https://github.com/facebook/react-native/blob/5c202cafd67237726d1b85608ebd7d301a84be8d/React/CxxBridge/RCTJSIExecutorRuntimeInstaller.mm#L18-L21), which is where the logs come out of the engine.

**Comment by mrousavy** [comment]
@alloy I've tried tracking it down like this:

* [`setUpDeveloperTools.js:L68-L77`](https://github.com/facebook/react-native/blob/master/Libraries/Core/setUpDeveloperTools.js#L68-L77) notices that `console._isPolyfilled` is false, so it logs that "warning" to my console (which obviously works, no idea why it doesn't just use it then?
* [`console.js:L546`](https://github.com/facebook/react-native/blob/master/packages/polyfills/console.js#L546) checks if the native console hook is available, and then [prepares the console polyfill](https://github.com/facebook/react-native/blob/master/packages/polyfills/console.js#L556-L573))
* [`JSIExecutor.cpp:L515`](https://github.com/facebook/react-native/blob/master/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp#L515-L537) binds the native console hook that we required in the step above, but somehow this fails so everything else also fails to polyfill.

**Comment by mrousavy** [comment]
Okay the code I linked doesn't even get called. It should get called with `RCTJSIExecutorRuntimeInstaller`, but in `RCTCxxBridge.mm` it enters [this `if`](https://github.com/facebook/react-native/blob/master/React/CxxBridge/RCTCxxBridge.mm#L434-L437), causing the installer to get skipped.

![Screenshot 2021-02-09 at 14 41 41](https://user-images.githubusercontent.com/15199031/107371755-edd24400-6ae4-11eb-9734-c979732fabf7.png)

**Comment by mrousavy** [comment]
Resolved! It was a reanimated issue. See: https://github.com/software-mansion/react-native-reanimated/pull/1704

**Comment by alloy** [comment]
Ah I see, good sleuthing :clap:

**Comment by KingAmo** [comment]
still have this problem with react-native-reanimated v2.0.0, hermes enabled in iOS
